POST http://localhost:3001/api/notes/
content-type: application/json

{
  "content": "test",
  "important": true
}

###
DELETE http://localhost:3001/api/notes/65994d33ee7a1f7bdfefbad1

###
GET http://localhost:3001/api/notes/

###
PUT http://localhost:3001/api/notes/659a8e7ece70552b69c695c6
content-type: application/json

{
  "content": "sample",
  "important": false
}

